### DISCUSSION TITLE
Show day / date  / month on different lines

### DISCUSSION THREAD

**Discussion by marksie1988** [totaldebug/atomic-calendar-revive#1190] [Showroom]
If you want to show the left hand day / date / month on separate lines, use the below code: 

**Before:**
![image](https://github.com/totaldebug/atomic-calendar-revive/assets/159166/7faa357d-a107-4bee-b191-e7b8419d5bef)

**After:**
![image](https://github.com/totaldebug/atomic-calendar-revive/assets/159166/20aec95a-8ea8-447b-9ee5-dabeb2f9a227)

```yaml
card_mod:
  style: |
    .event-left{
      display: flex;
      flex-direction: column !important;
      align-items: center;
    }
```
