### DISCUSSION TITLE
It seems 'untilText' and 'fullDayEventText' do not work

### DISCUSSION THREAD

**Discussion by mfabiani53** [totaldebug/atomic-calendar-revive#1288] [Support]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I set one calendar card:

But the text is still in English... Is that configuration correct? Or am i doing something wrong?

### Expected behaviour

No translation of some text in italian language

### Mode

Event (default)

### Card Version

9.2.0

### Home Assistant Version

2023.11.0

### Configuration

```shell
          - type: custom:atomic-calendar-revive
            entities:
              - entity: calendar.personale
                maxEventCount: 0
                maxDaysToShow: 60
                name: Personale
                color: red
                europeanDate: true
                untilText: "Fino a"
                fullDayEventText: "Tutto il giorno"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by github-actions** [comment]
Hello @mfabiani53, thank you for your interest in our work!
If this is a bug report, please provide your configuration and any screenshots that would assist troubleshooting, otherwise we can not help you.

**Comment by mfabiani53** [comment]
![Schermata 2023-11-03 alle 18 39 00](https://github.com/totaldebug/atomic-calendar-revive/assets/37701688/c81880f7-1db8-4197-b6cd-4b07a31e7848)

**Comment by marksie1988** [comment]
Hi @mfabiani53, 

It looks like you have global configuration options under the entity instead try this configuration:


```
- type: custom:atomic-calendar-revive
  entities:
    - entity: calendar.personale
      name: Personale
      color: red
  maxDaysToShow: 60
  europeanDate: true
  untilText: "Fino a"
  fullDayEventText: "Tutto il giorno"
```
