### DISCUSSION TITLE
Hide text/string from output

### DISCUSSION THREAD

**Discussion by jankete** [totaldebug/atomic-calendar-revive#1395] [Feature Requests]
I use the card for displaying the birthdays from my google contacts. On the calendar the events are named automatically like "Name hat Geburtstag". I would like have an option not to show / to hide the part "hat Geburtstag" (has birthday) on my list.

**Comment by hughsaunders** [comment]
I have a similar use case: One of my calendars has client appointments, and for a public dashboard I'd like to show that there is a client meeting, but not which client, so remove anything after client. I guess this could be done with a regex substituion `s/^client.*$/client/`

**Comment by marksie1988** [comment]
Implemented on the `beta` branch in c21f64f. Per-entity `titleReplace` accepts a list of `{from, to}` rules where `from` is a case-insensitive regex; empty `to` strips the match:

```yaml
entities:
  - entity: calendar.contacts_birthdays
    titleReplace:
      - from: ' hat Geburtstag$'
        to: ''
```

"Steven hat Geburtstag" becomes "Steven". Closing as implemented.
