### DISCUSSION TITLE
Week part change

### DISCUSSION THREAD

**Discussion by poudenes** [totaldebug/atomic-calendar-revive#1418] [Support]
Hi All,

How can I change this:

<img width="513" alt="Screenshot 2024-02-07 at 11 06 06" src="https://github.com/totaldebug/atomic-calendar-revive/assets/4399532/48ab6f5b-541c-4903-ae25-6e3f6ae3ed44">

In example on the site the week and numbers are on the left without the black line and blue line.

Im using:
Server:
Core: 2024.1.6
Supervisor: 2024.01.1
Operating System: 11.5
Frontend: 20240104.0

iMac:  MacOS 14.2.1, Safari: 17.2.1, Chrome: 121.0.6167.13, Firefox: 122.0

Yaml part of the calendar:

```
type: vertical-stack
title: Calendar's
cards:
  - type: vertical-stack
    cards:
      - type: custom:atomic-calendar-revive
        entities:
          - entity: calendar.work
            color: purple
            maxDaysToShow: 7
            showMultiDay: true
          - entity: calendar.ha_holidays
            name: Ha holidays
            color: blue
            maxDaysToShow: 13
          - entity: calendar.ha_events
            name: Ha events
            color: red
            maxDaysToShow: -19
          - entity: calendar.ha_birthdays
            name: Ha birthdays
            maxDaysToShow: 14
          - entity: calendar.funko
            name: Funko
            color: green
        calShowDescription: true
        dateFormat: LL
        defaultMode: Event
        dimFinishedEvents: false
        disableCalEventLink: false
        disableCalLocationLink: false
        firstDayOfWeek: 1
        fullDayEventText: All Day
        header-date: true
        hideDeclined: true
        hideFinishedEvents: true
        hoursFormat: HH:mm
        locationLinkColor: black
        locationIconColor: black
        maxDaysToShow: 30
        noEventsForTodayText: Nothing
        progressBarColor: yellow
        showCalendarName: true
        showColors: true
        showCurrentEventLine: true
        showDate: true
        showEventIcon: true
        showFullDayProgress: true
        showLastCalendarWeek: true
        showLoader: true
        showMonth: true
        showMultiDayEventParts: true
        showNoEventsForToday: true
        showProgressBar: true
        showRelativeTime: true
        showWeekDay: true
        showWeekNumber: true
        sortByStartTime: true
        time-remaining: true
        showLocation: true
        showDeclined: false
        showMultiDay: true
        allDayBottom: true
        refreshInterval: 15
        showDescription: true
        disableEventLink: false
        disableLocationLink: false
        showEventDate: true
```
