### DISCUSSION TITLE
maxHoursToShow instead of maxDaysToShow

### DISCUSSION THREAD

**Discussion by chgoeldi** [totaldebug/atomic-calendar-revive#1438] [Feature Requests]
Hi, I was looking for the feature to show events in the next X hours. E.g. I would like to see the next 24h instead of 1d. This would then give me todays events in the morning but already tomorrows events in the evening. 
Thank you for considering this request.
Best,
chg

**Comment by Trzinka** [comment]
```yaml
        enableModeChange: true
        maxEventCount: 5
        refreshInterval: 60
        calShowDescription: true
        firstDayOfWeek: 1
        **maxDaysToShow: 2**
        sortByStartTime: true
        showMonth: true
        hoursFormat: HH:mm
        showLocation: true
        showRelativeTime: true
        showLoader: false
        showMultiDay: true
        showMultiDayEventParts: true
```

**Reply by chgoeldi** [reply]
Thanks. Kinda but not exactly what I wanted to accomplish. In the morning I really only want to see what's up for today and in the evening what the next day brings. Above shows me that but also much more (cluttered view).

**Reply by Trzinka** [reply]
Ok. Have you viewed this document: https://docs.totaldebug.uk/atomic-calendar-revive/configuration/main.html?
Next https://docs.totaldebug.uk/atomic-calendar-revive/configuration/entity.html.

Maybe try it:
```yaml
maxDaysToShow: 2
startTimeFilter: 08:00
endTimeFilter: 00:00
```
There are really a lot of these options, so you have nothing else to do but try/fix.

**Comment by mhspelt** [comment]
@Trzinka your example will show all events for today and tomorrow, but only events starting after 8:00 on their start day, right? That is not what the feature request is.

@chgoeldi  I'd like to do the same. Did you find a workaround or combination of configuration settings that accomplishes this? Anyway, here's my +1 for this request.

**Reply by Trzinka** [reply]
Hello.

Unfortunately, as far as I know, there is no other way to display what you want (the next 24 hours).

The only thing that can be done with the above settings is (you must have the add-on installed: https://github.com/thomasloven/lovelace-card-mod) to add in the yaml view:
card_mod:
  style: |
    .current-day {
       color: green !important;
     }
This will show you the current day's date in green!

Another solution is javascript code, which I don't have enough knowledge for.

**Comment by mhspelt** [comment]
@chgoeldi  and anyone interested: since this does not seem to be a feature of this component, I have solved it using the brilliant [card-templater](https://github.com/gadgetchnnel/lovelace-card-templater).

```yaml
type: 'custom:card-templater'
entities:
  - entity: calendar.my_calendar
card:
  type: custom:atomic-calendar-revive
  entities:
    - entity: calendar.my_calendar
      name: My calendar
  # ... other config. ..
  noEventsForNextDaysText: No events tomorrow either
  noEventText: No more events today
  maxDaysToShow_template: "{% if now().hour >= 16 %} 2 {% else %} 1 {% endif %}"  
  ```

The main trick is in the last line, where _maxDaysToShow_ is set to 2 if the current hour of the day is at least 16.
