### DISCUSSION TITLE
Calendar Week View Option

### DISCUSSION THREAD

**Discussion by CStam14** [totaldebug/atomic-calendar-revive#1439] [Feature Requests]
This is an excellent highly-configurable calendar.  The only thing that's missing for me is a way to show a weekly calendar view.  This would allow more room for event details for the current week, which would be great for a family dashboard so you're able to see all event times for the next few days at a glance.

**Comment by Trzinka** [comment]
```yaml
        enableModeChange: true
        maxEventCount: 5
        refreshInterval: 60
        calShowDescription: true
        firstDayOfWeek: 1
        maxDaysToShow: 7
        sortByStartTime: true
        showMonth: true
        hoursFormat: HH:mm
        showLocation: true
        showRelativeTime: true
        showLoader: false
        showMultiDay: true
        showMultiDayEventParts: true
```
