### DISCUSSION TITLE
Display items on the calendar.

### DISCUSSION THREAD

**Discussion by Trzinka** [totaldebug/atomic-calendar-revive#1448] [Feature Requests]
Hi!
Is it possible to change the positions of the fields?

`From:`
![Calendar3](https://github.com/totaldebug/atomic-calendar-revive/assets/40424965/40d6e20a-605c-49a2-97b3-eae0f21f343a)

If the view could somehow be in this style (example of one event) `To:`
![Calendar2](https://github.com/totaldebug/atomic-calendar-revive/assets/40424965/51e5c6b7-04cb-40e7-bd69-dd0c99968c79)

**Comment by marksie1988** [comment]
You would most likely be able to do something like this with card mod and amending the CSS, however its not something the card can do.

**Reply by Trzinka** [reply]
Hi, thanks for the reply!

**By the way, not to forget that your work so far has already been done with distinction!**

`My wish is, a better representation of this below:`

![20240624-FP](https://github.com/totaldebug/atomic-calendar-revive/assets/40424965/4d97ece8-7080-40f2-bd88-bb3f0deedf4a)

`As you suggested card mod and CSS, I honestly don't know how to solve moving elements:`

![20240624-FP-DevTools](https://github.com/totaldebug/atomic-calendar-revive/assets/40424965/3b1007ac-2ca1-4a7d-bfbb-f82cf59bc3e4)

`I use card mod and CSS often and I have also adapted the current review to my needs, although your settings already allow a lot!`

_Do you have any advice on how to improve my current settings?_
```yaml
type: custom:atomic-calendar-revive
        card_mod:
          style: |
            ha-card {
              margin: 0px !important;
              padding: 0px !important;
              border-width: 0px !important;
              max-height: 75vh !important;
              background: transparent !important;
              scrollbar-width: none !important;
              }
            :host {
              font-size: 2vh !important;
              scrollbar-width: 0px !important;
              }  
            .header-date {
              font-size: 3.3vh !important;
              color: red !important;
              }
            .location-link {
              color: blue !important;
              }
            .single-event-container {
              grid-gap: 0px !important;
              }
        maxDaysToShow: 7
        maxEventCount: 13
        showLocation: false
        showMonth: true
        showWeekDay: true
        showLoader: false
        showDate: true
        showDescription: false
        showMultiDay: true
        showMultiDayEventParts: true
        language: sl
        allDayBottom: true
        refreshInterval: 15
        showHours: true
        hideFinishedEvents: true
        firstDayOfWeek: 1
        calEventTime: true
        sortByStartTime: true
        showProgressBar: false
        showFullDayProgress: false
        showRelativeTime: true
        europeanDate: true
        showTimeRemaining: true
        dateFormat: dddd, DD MMMM, YYYY.  HH:mm:ss
        entities:
          - entity: calendar.f1
            name: Formula 1
            color: '#00ccf1'
          - entity: calendar.moto_gp
            name: Moto GP
            color: '#FF5F1F'
          - entity: calendar.druzina
            name: Opravki družine
            color: pink
          - entity: calendar.prazniki_v_sloveniji
            name: Prazniki v sloveniji
            color: '#007fff'
          - entity: calendar.odvoz_odpadkov
            name: Odvoz odpadkov
            color: green
          - entity: calendar.robert
            name: Opravki Robert
            color: red
          - entity: calendar.rojstni_dnevi
            name: Rojstni dnevi
            color: gold
          - entity: calendar.kolesarstvo
            name: Kolesarstvo
            color: '#00ff3d'
        view_layout:
          grid-area: calendar
```

`I think I should use "programming language-TypeScript" to achieve what I want, unfortunately I don't have that knowledge.`
