### DISCUSSION TITLE
Change Colour of calendar entries

### DISCUSSION THREAD

**Discussion by abbottcam** [totaldebug/atomic-calendar-revive#1473] [Support] [answered]
Hello, Im trying to get my head slowly around the card mod, but in the meantime, how would I change the colour of a particular calendar?

**Comment by marksie1988** [comment]
For that you would need to use the "color" setting under the calendar entity.

**Reply by AfRotaker** [reply]
Pardon my ignorance but where would I find that?

**Reply by VincentClement1** [reply, marked as answer]
Select "Show Code Editor" when editing the atomic-calendar-revive card. 

Then under each calendar add "color: TheColorYouWant". See below:
```
 entities:
   - entity: calendar.test
     name: Test
     color: LightSkyBlue
```
