### DISCUSSION TITLE
Option to hide event hours on individual calendars

### DISCUSSION THREAD

**Discussion by ihelland** [totaldebug/atomic-calendar-revive#1511] [Feature Requests] [answered]
First of all; thank you for maintaining and developing this awesome addition to Home Assistant! 😍

The reasoning behind my request is that I use Atomic Calendar to display some public iCal calendars were I do not care about the event hours. See attached pictures for illustration.

By the way, I use https://github.com/tybritten/ical-sensor-homeassistant for import of the calendars.

I've tried to read all available documentation and I've also reviewed all feature requests, but couldn't find anything that was helpful. Hope my request is unique and sorry if it isn't!

![Skjermbilde 2024-07-01 103538](https://github.com/totaldebug/atomic-calendar-revive/assets/81987012/85d5fe03-3b96-4e0c-b1c3-8006a2e89df1)
![Skjermbilde 2024-07-01 103737](https://github.com/totaldebug/atomic-calendar-revive/assets/81987012/c0f3dca0-c05f-4828-b722-d21e6b21a7d4)

**Comment by marksie1988** [comment, marked as answer]
Implemented on the `beta` branch in de0a34a. Set `showHours` per-entity to override the global default:

```yaml
type: custom:atomic-calendar-revive
entities:
  - entity: calendar.family
  - entity: calendar.holidays_in_united_kingdom
    showHours: false   # hide times for the holiday feed only
```

Closing as implemented.
