### DISCUSSION TITLE
Color the icon of the calendar used

### DISCUSSION THREAD

**Discussion by cbjerg** [totaldebug/atomic-calendar-revive#1567] [Showroom]
![Screenshot 2024-09-11 at 10 04 29](https://github.com/user-attachments/assets/23af6560-20cf-402e-a5de-c108fca9f1c1)
I use individual icons for my calendars in my event list. To get this a bit nicer looking I have movedf the time of the events to be underneath the event name, and colored the icons to better tell them apart. I am using mdi:human-male-female-child for my family calendar, and mdi:human-male for my personal calendar. Also had to slightly expand the first grid column to accomodate the whole date

```css
card_mod:
  style: |
    .hours {
      margin-left: 24px;
    }
    .single-event-container {
      grid-template-columns: 0.6fr 2fr !important;
    }
    .event-icon {
      margin-right: 5px !important;
    }
    ha-icon.event-icon[icon="mdi:human-male-female-child"] {
      color: green !important;
    }
    ha-icon.event-icon[icon="mdi:human-male"] {
      color: red !important;
    }
```
