### DISCUSSION TITLE
Add option to style all day events separately from other events

### DISCUSSION THREAD

**Discussion by raetha** [totaldebug/atomic-calendar-revive#1571] [Feature Requests]
I tried to see if there was an existing class that seemed to cover all day events but it didn't appear so. They did get tracked as running events, which gets part way to my goal. That would just also capture the current active event, I believe.

My end goal is to change the background color of all day events to allow for easily skimming them for what they are.

Happy to test or assist in any way.

**Comment by marksie1988** [comment]
Hi! This is already possible — the card adds an `event-title-fullday` CSS class to all-day events in Event and Planner modes, and uses `summary-fullday-div-accepted` / `summary-fullday-div-declined` for all-day rows in the Calendar-mode day summary. You can target these with `card_mod` to give all-day events their own background, border, padding, etc.

Example (Event mode):

```yaml
type: custom:atomic-calendar-revive
entities:
  - calendar.family
card_mod:
  style: |
    .event-title.event-title-fullday {
      background-color: rgba(86, 100, 86, 0.35);
      padding: 2px 6px;
      border-radius: 4px;
    }
```

Closing as already implemented. These classes weren't called out in the styling guide — we'll add them so they're easier to discover.
