### DISCUSSION TITLE
Event list option: Show past days

### DISCUSSION THREAD

**Discussion by phieb** [totaldebug/atomic-calendar-revive#1578] [Feature Requests]
Hey there!
I'd like to always see the complete week of my events.
Even if it's already Wednesday I want to see Monday and Tuesday with all great things I've already done.
e.g. hideFinishedDays: False (default True)

First I tried to just use templating and the startDaysAhead property. But I quickly figured templating isn't supported.
Workaround: Create a config for each day of the week and show only the one for today while using startDaysAhead. (not as nice though - right?)

**Comment by marksie1988** [comment]
Implemented on the `beta` branch in 6044a78 — set `showPastDaysOfWeek: true` on the card config (Event mode) and the visible window anchors to the start of the current week instead of today.

```yaml
type: custom:atomic-calendar-revive
entities:
  - calendar.family
defaultMode: Event
maxDaysToShow: 7
showPastDaysOfWeek: true
firstDayOfWeek: 1   # Monday
```

On a Wednesday this surfaces Mon–Sun (3 past days + today + 3 future) rather than Wed–Tue. Past events keep their real date label and `dimFinishedEvents` still applies. Will ship in the next `beta` release. Closing as implemented.
