### DISCUSSION TITLE
Non-Reoccuring events more promenent or different colour

### DISCUSSION THREAD

**Discussion by TheBartoMan** [totaldebug/atomic-calendar-revive#1579] [Feature Requests]
I would love to make the non-reoccuring events stand out more.

We have lots of re-occuring events that happen many days per week. Its the one offs that we always miss and wish they could stand out more on the calander please? Bold? Different colour?

**Comment by marksie1988** [comment]
Implemented on the `beta` branch in c5206a1. Every `.event-title` now carries a `.recurring` class when the event is part of a recurring series. Target it (or its absence) with card_mod:

```yaml
card_mod:
  style: |
    /* dim recurring events so one-offs pop */
    .event-title.recurring {
      opacity: 0.7;
      font-style: italic;
    }
    /* or: highlight one-offs only */
    .event-title:not(.recurring) {
      font-weight: bold;
      color: var(--accent-color);
    }
```

Closing as implemented.
