### DISCUSSION TITLE
changing event-title based on contents

### DISCUSSION THREAD

**Discussion by brucebuchan89** [totaldebug/atomic-calendar-revive#1587] [Showroom]
Hi Everyone,
I'm trying to change the colour of the event-title based on if its for myself, my wife or kids. There names are in the event description. Can't get the keyword aspect to work; I know the card-mod is working as i've been able to apply other styles to the event-title on its own. Anyone any ideas? Thanks

type: custom:atomic-calendar-revive
entities:
  - entity: calendar.bruce_calendar_calendar
    name: Calendar
card_mod:
  style: |
    .event-title:contains("Elsie") {
      color: yellow !important;
    }

**Comment by schmerg** [comment]
I did something similar by repeating the same calendar entity with a different allowlist (simple case insensitive regex to only add events that match title) and a different color
Hence to get my bin collections showing Recycling days in blue (for a blue bin) and the General collection in green (green bin) I use the config below 

```

type: custom:atomic-calendar-revive
name: Bins
defaultMode: Event
enableModeChange: true
showHours: false
showRelativeTime: true
showEventDate: true
maxDaysToShow: 14
entities:
  - entity: calendar.london_borough_of_harrow
    allowlist: Recycling
    color: blue
  - entity: calendar.london_borough_of_harrow
    allowlist: General
    color: green

```

to get a display like

![image](https://github.com/user-attachments/assets/be31fe1f-764a-4481-b9ac-da07113cae29)
