### DISCUSSION TITLE
Show a weeks schedule even if day has passed

### DISCUSSION THREAD

**Discussion by Shaun-Harrison** [totaldebug/atomic-calendar-revive#1600] [Feature Requests]
Sorry if this doesn't make much sense, its a hard once to explain, but what I'd like is for the calendar to basically show 7 days worth of events, with it always starting on Monday and ending on Sunday. If the events have passed, it would show as crossed out or whatever the default is at this time.

**Comment by JonteP** [comment]
+1 on this one. Exactly what I am looking for.

**Comment by zavjah** [comment]
+1

**Comment by marksie1988** [comment]
Implemented on the `beta` branch in 6044a78 (same change as #1578). Set `showPastDaysOfWeek: true` and the 7-day window anchors to the start of the current week (respecting `firstDayOfWeek` — set it to `1` for Mon–Sun). Past events keep their real date label and `dimFinishedEvents` strikes through finished ones.

```yaml
type: custom:atomic-calendar-revive
entities:
  - calendar.family
defaultMode: Event
maxDaysToShow: 7
showPastDaysOfWeek: true
firstDayOfWeek: 1   # Mon–Sun
```

Closing as implemented.
