### DISCUSSION TITLE
Feature request to rename entities (Calendar Entrys)

### DISCUSSION THREAD

**Discussion by Kuschi** [totaldebug/atomic-calendar-revive#1605] [Feature Requests]
Hi, i want to request a option to rename the event titles in the atomic-calendar-revive card.
I would suggest adding this feature in the entity options, so it can be entered for each calendar with different options.

So we can use TAGs like Child, Mum, Dad or whatever you want in the front of the event title in one calendar, filter them to show only Mum related entries and then show them in HA without the (technical) Tags.

Below a sample how it can be used from customer side:
```
type: custom:atomic-calendar-revive
name: Calendar
entities:
  - entity: calendar.daddy
    name: Daddy
    - rename
      from: Daddy Work
      to: Work
      from: Birthday Grandpa
      to: Grandpa
  - entity: calendar.mommy
    name: mommy
```

**Comment by marksie1988** [comment]
Implemented on the `beta` branch in c21f64f. `titleReplace` is per-entity and accepts an ordered list of `{from, to}` regex rewrites:

```yaml
entities:
  - entity: calendar.daddy
    name: Daddy
    titleReplace:
      - from: '^Daddy '
        to: ''
      - from: '^Birthday Grandpa$'
        to: 'Grandpa'
  - entity: calendar.mommy
    name: Mommy
```

"Daddy Work" → "Work", "Birthday Grandpa" → "Grandpa". Closing as implemented.
