### DISCUSSION TITLE
Font size of a given Calendar

### DISCUSSION THREAD

**Discussion by FaBRiK74** [totaldebug/atomic-calendar-revive#1617] [Feature Requests]
I have 4 different calendar entities shown in atomic-calendar-revive, but there is a main one. It ha a different color, but I'd like to have a little bit bigger font size for this specific calendar.

**Comment by NilsNijenhuis** [comment]
that would be nice, but also the possibility to maken one agenda use 'font-weight' as styling so that agenda jump more out of te overview

**Comment by marksie1988** [comment]
Implemented on the `beta` branch in de0a34a. Set `fontSize` per-entity — numbers are treated as `px`, strings (`120%`, `1.1em`) pass through verbatim:

```yaml
entities:
  - entity: calendar.family   # the important one
    fontSize: 18
    fontWeight: bold
  - entity: calendar.holidays
    fontSize: '90%'
```

Closing as implemented.
