### DISCUSSION TITLE
font-weight adjustable per calendar

### DISCUSSION THREAD

**Discussion by NilsNijenhuis** [totaldebug/atomic-calendar-revive#1620] [Feature Requests]
i would like to ajust the font-weight per agenda. I have a overview of 3 agenda's and would like to give one agenda the 'font-weight: bold'. So that this calendar is more noticeable

**Comment by marksie1988** [comment]
Implemented on the `beta` branch in de0a34a. Set `fontWeight` per-entity — accepts CSS keywords (`bold`) or numeric weights (`700`):

```yaml
entities:
  - entity: calendar.important
    fontWeight: bold
  - entity: calendar.background
```

Closing as implemented.
