### DISCUSSION TITLE
Per calendar showDescription

### DISCUSSION THREAD

**Discussion by dahlma** [totaldebug/atomic-calendar-revive#1660] [Feature Requests]
I would love to be able to control the showDescription per calendar, so I only show the description for the kids calendars but hides mine.. 

Thank you for your great work, we as a family use it every day.

**Comment by marksie1988** [comment]
Implemented on the `beta` branch in de0a34a. Set `showDescription` per-entity to override the global default:

```yaml
type: custom:atomic-calendar-revive
showDescription: false   # global default
entities:
  - entity: calendar.kids
    showDescription: true   # show descriptions for kids' calendar only
  - entity: calendar.mine
```

Closing as implemented.
