### DISCUSSION TITLE
Calendar in English

### DISCUSSION THREAD

**Discussion by Hanien1977** [totaldebug/atomic-calendar-revive#464] [Support] [answered]
Suddenly my calendar is shown in English, previously in were in Danish and European time mode (24  hour)

![image](https://user-images.githubusercontent.com/57419516/127321978-a868f903-2c31-4d3a-b3e9-dcbf26727f53.png)

Day names are in English and times is in AM/PM mode.

My Home Assistant is set to Danish.

My config is:
          - type: custom:atomic-calendar-revive
            style:
              top: 35%
              left: 38.5%
              width: 27%
            title: true
            progressBar: true
            maxDaysToShow: 21
            showMonth: true
            showWeekDay: true
            showLoader: false
            showProgressBar: false
            dateTopFormat: DD/MM
            dateBottomFormat: dddd
            highlightToday: true
            showEventOrigin: true
            showDescription: true
            europeanDate: true
            eventTitleSize: 150
            dateSize: 130

What has changed?

**Comment by evanschisenga** [comment]
The days of view

**Comment by evanschisenga** [comment]
Time it's in hours

**Reply by evanschisenga** [reply]
Hours

**Comment by Hanien1977** [comment]
@evanschisenga - I don't understand your suggestions? 
My issue is that I want the name of the day in Danish, not English (Fri should be Fre), and the time in 24 hour interval (3 pm should be 15)

**Reply by evanschisenga** [reply]
Dart

**Comment by marksie1988** [comment]
You should be able to do 

`language: de`

**Reply by Hanien1977** [reply]
language work, but doesn't support Danish

In the documentation it says on 'language':
_Force language change. If not set, default HA language is used._

My HA is set for Danish, but it still writes days in English.

The documentation on hoursFormat, says:
24h You can set 12h, 24h or custom,

But both leaving the string out og adding hoursFormat: 24h still gives me 12h format

**Reply by marksie1988** [reply]
What version is displayed in your browser console for atomic calendar?

All I can think now is you are on an old version, as `de` is supported and it should now be 24h by default in the latest versions

**Reply by Hanien1977** [reply]
I just updated everything.
I'm running: 
- HA: core-2021.7.4
- Atomic v4.5.0

But still have the problem

**Reply by marksie1988** [reply]
Ok thanks im not sure why that is  still an issue then: 

![image](https://user-images.githubusercontent.com/159166/127743436-3b6375c3-07bf-456f-ac1e-48ce9abdf4ad.png)

that is using this config:

```
type: custom:atomic-calendar-revive
name: Calendar Card
entities:
  - entity: calendar.test_calendar
    icon: mdi:shield
    color: green
progressBar: true
maxDaysToShow: 21
showMonth: true
showWeekDay: true
showLoader: false
showProgressBar: false
highlightToday: true
europeanDate: true
eventTitleSize: 150
dateSize: 130
language: de

```


The following options in your config are not config options in this card:

```
showEventOrigin: true
showDescription: true
dateTopFormat: DD/MM
dateBottomFormat: dddd
style:
top: 35%
left: 38.5%
width: 27%
```

If you still have issues i would suggest trying to restart HA and then clearing your browser cache, I can confirm that this isn't a bug with the card otherwise I would see the same issue on my test server.
