### DISCUSSION TITLE
Nextcloud integration =?

### DISCUSSION THREAD

**Discussion by ami6de** [totaldebug/atomic-calendar-revive#485] [Support]
Is there a way to show calendar entries from a Nextcloud CalDAV instance ?

**Comment by marksie1988** [comment]
Yes, if you add your caldav calendars to home assistant you add them to the card the same as any other calendar using the entity name.

**Comment by ami6de** [comment]
Could you describe the NC integration in detail? My calendars are always shown as empty... ("no events in the next few days").

i wrote a card as follows:

```type: custom:atomic-calendar-revive
entities:
  - entity: calendar.school
    titleColor: purple
    icon: mdi:home-heart
    color: purple
firstDayOfWeek: 1
maxDaysToShow: 7
refreshInterval: 60
showMonth: true
showWeekDay: true
showLastCalendarWeek: true
calShowDescription: true
```

And in ```configuration.yaml``` i defined this:

```
calendar:
  - platform: caldav
    username: <username>
    password: !secret caldav_nextcloud
    url: https://<url>/remote.php/dav
    calendars:
      - 'family'
      - 'school'
 ```

And the calendars are filled with entries.
