### DISCUSSION TITLE
Is google_calendars.yaml required?

### DISCUSSION THREAD

**Discussion by Lifth1309** [totaldebug/atomic-calendar-revive#710] [Support] [answered]
Hi,
is it possible to use this integration without the google_calendars.yaml? I've set up the google calendar integration just recently (after 2022.06). It seems to work fine, but no google_calendars.yaml-file was created and populated - just as it's stated on the integration page:
"The integration supports additional configuration from a file google_calendars.yaml which is available for existing users before version 2022.06. This file is no longer automatically populated."
I'd love to try the atomic-calendar-revive card, but it can't find any entities. Is that because of the missing yaml-file?
Greetings!

**Comment by marksie1988** [comment, marked as answer]
Hi There, 

This is only required if you are not seeing all of the events that you would expect to see. 

The configuration file requires the following for each google calendar: 

cal_id - string: The Google generated unique id for this calendar.
entities - list: 
  device_id - string: The name that all your automations/scripts will use to reference this device..
  ignore_availability - boolean: (optional, default: true) Should we respect free/busy flags?
  name - string: name of the sensor
  max_results - number: how many calendar entries to retrieve. 

example below:

```yaml
- cal_id: myemail@gmail.com
  entities:
  - device_id: my_email_gmail_com
    ignore_availability: true
    name: myemail@gmail.com
    max_results: 100

```
