### ISSUE TITLE
showMultiDay option shows no multi-day events at all

### ISSUE THREAD

**Issue by jensrossbach** [totaldebug/atomic-calendar-revive#1010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I set option `showMultiDay` to `true`, multi-day events are not shown at all anymore.

### Expected behaviour

I see multi-day events on every day as the option suggests.

### Card Version

7.3.0

### Home Assistant Version

2023.4.6

### Configuration

```shell
- type: custom:atomic-calendar-revive
    entities:
    - entity: calendar.o365_deutsche_feiertage
        name: Feiertage
        color: rgb(220, 0, 80)
        icon: mdi:flag-variant
    - entity: calendar.abfallkalender
        name: Müllabfuhr
        color: rgb(0, 220, 250)
        icon: mdi:trash-can-outline
    - entity: calendar.schulferien
        name: Schulferien
        color: rgb(50, 150, 50)
        icon: mdi:school
    - entity: calendar.o365_geburtstagskalender
        name: Geburtstage
        color: rgb(200, 100, 250)
        icon: mdi:cake-variant
    - entity: calendar.o365_familie
        name: Familie
        color: rgb(0, 160, 255)
        icon: mdi:human-male-female-child
    defaultMode: Calendar
    showLoader: false
    disableEventLink: true
    disableLocationLink: true
    disableCalEventLink: true
    disableCalLocationLink: true
    disableCalLink: true
    calEventTime: true
    showMultiDay: true
    showMultiDayEventParts: true
    fullDayEventText: Ganztägig
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bkr1969** [comment]
Here is my code, though it shouldn't be necessary for reporting this problem.  Any time you try to edit the caledar, a ```-null``` is inserted and invalidates the visual editor.

```
type: custom:atomic-calendar-revive
name: Calendar Card
entities:
  - null
  - entity: calendar.anylist_meal_plan
    name: Anylist meal plan
    color: grey
    icon: mdi:silverware-fork-knife
  - entity: calendar.ohio_state_buckeyes
    name: Ohio state buckeyes
    icon: mdi:football
    color: maroon
enableModeChange: true
defaultMode: Calendar
calShowDescription: true
showLastCalendarWeek: false
disableCalEventLink: false
disableCalLink: true
firstDayOfWeek: 0
maxDaysToShow: 10
refreshInterval: 60
showDate: true
showRelativeTime: true
showMultiDay: false
hideDuplicates: true
sortByStartTime: true
showCurrentEventLine: true
calEventTime: true
showMonth: true
showFullDayProgress: true
showWeekDay: false
showEventIcon: true
showCalendarName: true
showHiddenText: false
showDatePerEvent: false
disableCalLocationLink: false
showMultiDayEventParts: true
hideFinishedEvents: false
untilText: 'true'
```

**Comment by bkr1969** [comment]
Same problem.  Here is my code:

```
Here is my code, though it shouldn't be necessary for reporting this problem. Any time you try to edit the caledar, a -null is inserted and invalidates the visual editor.

type: custom:atomic-calendar-revive
name: Calendar Card
entities:
  - null
  - entity: calendar.anylist_meal_plan
    name: Anylist meal plan
    color: grey
    icon: mdi:silverware-fork-knife
  - entity: calendar.ohio_state_buckeyes
    name: Ohio state buckeyes
    icon: mdi:football
    color: maroon
enableModeChange: true
defaultMode: Calendar
calShowDescription: true
showLastCalendarWeek: false
disableCalEventLink: false
disableCalLink: true
firstDayOfWeek: 0
maxDaysToShow: 10
refreshInterval: 60
showDate: true
showRelativeTime: true
showMultiDay: false
hideDuplicates: true
sortByStartTime: true
showCurrentEventLine: true
calEventTime: true
showMonth: true
showFullDayProgress: true
showWeekDay: false
showEventIcon: true
showCalendarName: true
showHiddenText: false
showDatePerEvent: false
disableCalLocationLink: false
showMultiDayEventParts: true
hideFinishedEvents: false
untilText: 'true'
```

**Comment by bkr1969** [comment]
Same problem.  Here is my code. Please ignore the ```-null``` as that is brought up in another issue.

```
type: custom:atomic-calendar-revive
name: Calendar Card
entities:
  - null
  - entity: calendar.anylist_meal_plan
    name: Anylist meal plan
    color: grey
    icon: mdi:silverware-fork-knife
  - entity: calendar.ohio_state_buckeyes
    name: Ohio state buckeyes
    icon: mdi:football
    color: maroon
enableModeChange: true
defaultMode: Calendar
calShowDescription: true
showLastCalendarWeek: false
disableCalEventLink: false
disableCalLink: true
firstDayOfWeek: 0
maxDaysToShow: 10
refreshInterval: 60
showDate: true
showRelativeTime: true
showMultiDay: false
hideDuplicates: true
sortByStartTime: true
showCurrentEventLine: true
calEventTime: true
showMonth: true
showFullDayProgress: true
showWeekDay: false
showEventIcon: true
showCalendarName: true
showHiddenText: false
showDatePerEvent: false
disableCalLocationLink: false
showMultiDayEventParts: true
hideFinishedEvents: false
untilText: 'true'
```
