### ISSUE TITLE
Show date on days without events.

### ISSUE THREAD

**Issue by dcode** [totaldebug/atomic-calendar-revive#1098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've created a dashboard with a grid layout and each grid has a single day in the event layout with each day incremented with "startDaysAhead" (see screenshot) using the declutter card. On days where there is nothing scheduled, it just says "No events". Is it possible to still have the date present?

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/171574/41b8afcd-5418-4022-ad92-b70b2375b8dc)

Here's my card config:

```yaml
-  type: custom:atomic-calendar-revive
   defaultMode: Event
   enableModeChange: false
   showWeekDay: true
   entities:
     - entity: calendar.derek
       name: Derek
       color: '#51f651'
     - entity: calendar.holidays_us
       name: Holidays
   startDaysAhead: 0
   maxDaysToShow: 1
   refreshInterval: 600
   eventTitle: Busy
   hideFinishedEvents: false
   calShowDescription: true
   showMultiDay: true
   showCalendarName: true
   showNoEventDays: true
   showNoEventsForToday: false
   compactMode: false
```

### Expected behaviour

I expected the day of the week and date number to still show on days where there are no events when `showNoEventDays` is true.

### Possible Solutions

I'm not sure if my expected behavior breaks things for other usecases. If not, maybe this is a simple bug fix. If it would break something, maybe another flag that enables this behavior.

### Mode

Event (default)

### Context / Reason

The bigger picture is having a list of events for each day in a large dashboard so that my whole family sees what's coming up for the next 7 days (I have 2 rows of 4 grid squares).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
