### ISSUE TITLE
Allow the use of entity_picture as part of the card header/title

### ISSUE THREAD

**Issue by swampylee** [totaldebug/atomic-calendar-revive#1102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

You can specify a title for the card but can't use an entity_picture or icon as part of the card title. This would be really useful for things like sporting teams upcoming games if the card could show a user defined image (like a football teams motif).

### Expected behaviour

As above

### Mode

Both

### Context / Reason

As above. Would allow the card to look a lot nicer - you can embed an icon in the title like this:

        name: 🐩 Dog Grooming

But it would be nicer to be able to define an image to be shown rather than be restricted by just emojis from sites like https://emojipedia.org/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
I'm not sure if this would be possible, are you aware of any other cards that have this functionality? As I may be able to see how they achieved it.

**Comment by swampylee** [comment]
> I'm not sure if this would be possible, are you aware of any other cards that have this functionality? As I may be able to see how they achieved it.

Hi, this is one example:

```
  - type: custom:uptime-card
    entity: binary_sensor.smarttechknow
    icon: /local/smarttechknow.png
    name: SmartTechKnow.com
    hours_to_show: 24
    status_adaptive_color: true
    color:
      icon: grey
      title: white
```
![image](https://github.com/totaldebug/atomic-calendar-revive/assets/52431327/3250d7f8-7b8c-4efb-a4b6-6fa66d0084b4)
