### ISSUE TITLE
Add the calendar name of each entity

### ISSUE THREAD

**Issue by Veher-el** [totaldebug/atomic-calendar-revive#1114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If we have several calendars to display in event mode, it is not possible to distinguish them (except by icon)

(I have tried showCalendarName but it seems not working…)

### Expected behaviour

Would it be possible to add the following option : 

- display the calendar name of each entity 

Thank you in advance for your help

### Possible Solutions

Displayd Prior to the event name or below

### Mode

Event (default)

### Context / Reason

Provide an better readable and understandable event list when we are using calendar event mode with several calendars.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Setting `showCalendarName: true` will show the calendar name at the right side of the card. 

I have this setup on my HA and it is working. If you could provide your configuration and a screenshot of what you currently see that would help me troubleshoot

**Comment by Veher-el** [comment]
Hello @marksie1988 
I have already test it in event mode but nothing is displayed on the right side.

Indeed, if showCalendarName is already implement, may be it is a bug.


![image](https://github.com/totaldebug/atomic-calendar-revive/assets/88648983/16870bfb-0f9a-4a62-bc42-fe738ecfde04)

my configuration : 

- Home Assistant 2023.8.4
- Supervisor 2023.08.1
- Operating System 10.5
- Interface utilisateur : 20230802.1 - latest
- Atomic Calendar Revive v 7.6.1

**Comment by marksie1988** [comment]
I would need the configuration from the card, if you edit the card, click show code editor in the bottom left and paste the yaml on GitHub (feel free to change calendar names to something else if they are sensitive but don't remove them)

**Comment by marksie1988** [comment]
Ok your entity configuration is incorrect, try this:

```
entities:
        - entity: calendar.perso
          name: XXX
          icon: mdi:human-male
        - entity: calendar.us
          name: Us
          icon: mdi:human-male-female
        - entity: calendar.family
          name: Family
          icon: mdi:human-male-female-child
```
