### ISSUE TITLE
Multiday Events still broken. (iCal)

### ISSUE THREAD

**Issue by bkr1969** [totaldebug/atomic-calendar-revive#1147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Multiday events still do not show at all when set to true and only show on first day when set to false.

### Expected behaviour

Multiday event shown on every day

### Mode

Calendar

### Card Version

7.7.2

### Home Assistant Version

2023.9.2

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Newest Card
entities:
  - entity: calendar.family_stuff
    name: Family Stuff
    icon: mdi:human-male-female-child
    color: white
  - entity: calendar.garbage_collection
    name: Garbage Collection
    icon: mdi:delete
    color: white
  - entity: calendar.ohio_state_buckeyes
    name: Ohio state buckeyes
    icon: mdi:football
enableModeChange: true
firstDayOfWeek: 0
defaultMode: Calendar
linkTarget: _blank
showDeclined: true
sortByStartTime: true
showDate: true
hideDuplicates: true
showRelativeTime: false
showMultiDayEventParts: true
showMultiDay: true
showCalendarName: true
showHiddenText: false
showEventIcon: true
showWeekNumber: false
showLastCalendarWeek: true
disableCalEventLink: false
calShowDescription: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bkr1969** [comment]
I would be happy to test any fixes you make before you close this issue as fixed.

**Comment by marksie1988** [comment]
> I would be happy to test any fixes you make before you close this issue as fixed.

You can comment on the old issue and i will re-open rather than creating a new issue each time. 

I have just done another test with your config on the latest version, I have entries from both caldav and google calendar and its all showing as expected

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/159166/90e5a21f-633e-4180-91b3-2bd7cddc819a)

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/159166/c2bee7e2-ebca-4438-a73e-4965de90638a)

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/159166/9d737ac9-8f0e-4452-aaa9-39036e2d2fe7)

**Comment by bkr1969** [comment]
Can you post your config?

**Comment by marksie1988** [comment]
I'm using the config that you posted above: 

```
type: custom:atomic-calendar-revive
name: test
entities:
  - entity: calendar.xxxx
    name: my cal
    icon: mdi:abacus
  - entity: calendar.xxxx
    name: xxxx
    icon: mdi:shield
  - entity: calendar.xxxx
    name: xxxx
    icon: mdi:home-group
  - entity: calendar.personal
    name: Personal
    icon: mdi:power-socket
enableModeChange: true
firstDayOfWeek: 0
defaultMode: Calendar
linkTarget: _blank
showDeclined: true
sortByStartTime: true
showDate: true
hideDuplicates: true
showRelativeTime: false
showMultiDayEventParts: true
showMultiDay: true
showCalendarName: true
showHiddenText: false
showEventIcon: true
showWeekNumber: false
showLastCalendarWeek: true
disableCalEventLink: false
calShowDescription: true

```

**Comment by bkr1969** [comment]
So how is your caldav set up? I can't figure out why mine is still not working.

**Comment by marksie1988** [comment]
as per: https://www.home-assistant.io/integrations/caldav/

```
calendar:
  - platform: caldav
    username: owncloud
    password: xxxx
    url: http://172.16.20.201/owncloud/remote.php/dav
```

The card uses the home assistant Rest API to get the events, home assistant now uses a uniform API so no matter what calendar you use, if its setup correctly and its showing in home assistant then the same data is displayed no matter if its caldav or google calendar. 

Do you see the events when looking in the normal home assistant calendar? if not that would show an issue with the integration of the calendar.
