### ISSUE TITLE
Parameter maxDaysToShow not consiered correctly anmyore

### ISSUE THREAD

**Issue by Bastian007** [totaldebug/atomic-calendar-revive#1154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since version [v7.7.1](https://github.com/totaldebug/atomic-calendar-revive/releases/tag/v7.7.1) or [v7.7.2](https://github.com/totaldebug/atomic-calendar-revive/releases/tag/v7.7.2) the parameter maxDaysToShow is not considered correctly anymore.

I have one card for birthdays, maxDaysToShow is equal to 1 to show only todays birthdays (all-day events) 
but the card is showing also the (2) birthdays of the next day.
![image](https://github.com/totaldebug/atomic-calendar-revive/assets/12425311/0c5d1a2c-26ed-428e-bcfc-58f9b87ed11e)

### Expected behaviour

Parameter maxDaysToShow is consiered correctly 

### Mode

Event (default)

### Card Version

v8.0.0

### Home Assistant Version

2023.9.2

### Configuration

```shell
type: custom:atomic-calendar-revive
enableModeChange: true
entities:
  - entity: calendar.geburtstage
    name: Geburtstage (Bastian)
    icon: mdi:cake-variant
    showMultiDay: true
  - entity: calendar.geburtstage_2
    name: Geburtstage (Mareike)
    icon: mdi:cake-variant
    showMultiDay: true
firstDayOfWeek: 1
maxDaysToShow: 1
refreshInterval: 300
hideDuplicates: true
showProgressBar: true
showCurrentEventLine: false
showMonth: false
showDescription: false
showWeekDay: false
disableEventLink: false
disableLocationLink: false
showNoEventsForToday: true
showFullDayProgress: false
showEventIcon: true
showHiddenText: false
showCalendarName: false
showWeekNumber: false
calShowDescription: false
showLastCalendarWeek: false
disableCalEventLink: true
disableCalLocationLink: true
disableCalLink: true
dimFinishedEvents: true
hideFinishedEvents: false
showRelativeTime: false
showMultiDay: false
showDeclined: false
showMultiDayEventParts: false
showDate: false
showLoader: false
showLocation: true
showDatePerEvent: false
showEventDate: false
language: de
fullDayEventText: ganztags
noEventText: keine Geburtstage heute
noEventsForNextDaysText: keine Geburtstage in den kommenden Tagen
dateFormat: L
allDayBottom: false
sortBy: start
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bastian007** [comment]
Thanks for checking!
Actually I've upgraded already to 8.0.0.
I also did a reboot of HA and the dashboard (not only the preview of the card editor) is showing the event of the next day.
I created 3 birthdays in a row: today, tomorrow and the day after.
I just added basic config (only one calendar source) and still can reproduce the issue:
![image](https://github.com/totaldebug/atomic-calendar-revive/assets/12425311/aa01e383-0063-4f2a-9094-db8e350797bd)

```
type: custom:atomic-calendar-revive
name: Calendar Card
enableModeChange: true
entities:
  - entity: calendar.geburtstage
    name: Geburtstage (Bastian)
    showMultiDay: false
firstDayOfWeek: 1
maxDaysToShow: 1
refreshInterval: 60
hideDuplicates: false
showProgressBar: false
showCurrentEventLine: false
showMonth: false
showDescription: false
showWeekDay: false
disableEventLink: false
disableLocationLink: false
showNoEventsForToday: true
showFullDayProgress: false
showEventIcon: false
showHiddenText: false
showCalendarName: false
showWeekNumber: false
calShowDescription: false
showLastCalendarWeek: false
disableCalEventLink: false
disableCalLocationLink: false
disableCalLink: false
dimFinishedEvents: false
hideFinishedEvents: false
showRelativeTime: false
showMultiDay: false
showDeclined: false
showMultiDayEventParts: false
showDate: false
showLoader: false
showLocation: false
showDatePerEvent: false
showEventDate: false
language: en
fullDayEventText: ganztags
noEventText: keine Geburtstage heute
noEventsForNextDaysText: keine Geburtstage in den kommenden Tagen
dateFormat: L
allDayBottom: false
sortBy: start
```
