### ISSUE TITLE
Calendar not showing some events and showing events not from today

### ISSUE THREAD

**Issue by kaizersoje** [totaldebug/atomic-calendar-revive#1244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have created a calendar with the following code. 

```yaml
type: custom:atomic-calendar-revive
name: Home Calendar
entities:
  - entity: calendar.home_calendar
    icon: mdi:home
    color: DARKORANGE
enableModeChange: true
defaultMode: Event
fullDayEventText: All day
untilText: Until
showColors: true
maxDaysToShow: 7
maxEventCount: 6
showLocation: true
showMonth: true
eventTitleColor: BURLYWOOD
locationIconColor: AZURE
locationLinkColor: GAINSBORO
dimFinishedEvents: true
finishedEventOpacity: 0.6
showProgressBar: true
nameColor: DARKKHAKI
calWeekDayColor: '#b8490d'
calDayColor: rgb(179,222,120)
defaultCalColor: '#FF6347'
sortByStartTime: true
showRelativeTime: true
hideFinishedEvents: true
allDayBottom: true
showWeekDay: false
showDescription: false
showCurrentEventLine: false
startDaysAhead: -1
```
This is what it looks like. Note the start date in the screenshot.
![image](https://github.com/totaldebug/atomic-calendar-revive/assets/54566217/78b42223-1ea5-455b-8e05-bcb2d2ac9474)

Now after adding a blocklist option to hide some events this is what I see, Note the start date in the screenshot.

```yaml
type: custom:atomic-calendar-revive
name: Home Calendar
entities:
  - entity: calendar.home_calendar
    icon: mdi:home
    color: DARKORANGE
    blocklist: (Family|talk)
enableModeChange: true
defaultMode: Event
fullDayEventText: All day
untilText: Until
showColors: true
maxDaysToShow: 7
maxEventCount: 6
showLocation: true
showMonth: true
eventTitleColor: BURLYWOOD
locationIconColor: AZURE
locationLinkColor: GAINSBORO
dimFinishedEvents: true
finishedEventOpacity: 0.6
showProgressBar: true
nameColor: DARKKHAKI
calWeekDayColor: '#b8490d'
calDayColor: rgb(179,222,120)
defaultCalColor: '#FF6347'
sortByStartTime: true
showRelativeTime: true
hideFinishedEvents: true
allDayBottom: true
showWeekDay: false
showDescription: false
showCurrentEventLine: false
startDaysAhead: -1
```

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/54566217/268db8bd-136e-44fa-b30c-d972d153735c)

### Expected behaviour

I should be seeing all the events using the first code with the start date from Oct 20. The events are not ordered by start time as well. This has been raised in issue #1240.

### Mode

Event (default)

### Card Version

9.1.0

### Home Assistant Version

2023.10.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
