### ISSUE TITLE
Add CSS class to summary on Calendar mode

### ISSUE THREAD

**Issue by CumpsD** [totaldebug/atomic-calendar-revive#540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently in Calendar mode there is a summary `div` but it has no CSS class.

![image](https://user-images.githubusercontent.com/1201644/142237336-26a223f9-659e-4037-89f9-5fcd8c56fa3e.png)

### Expected behaviour

It would be nice to have a CSS class on this div, and even better an extra class if there are no summary events.

This would allow me to style it better.

Currently I can style it with this:

```css
    .calTableContainer + div {
      padding-left: 8px;
      margin-top: 4px;
      padding-bottom: 4px;
      border: 1px solid rgba(86, 86, 86, .35)
    }
```

But this will also style it when there are no items.

### Context / Reason

Add a `.calSummary` and `.calEmptySummary` class to the div?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CumpsD** [comment]
In the mean time, I just figured out how to hide it ;)

```css
    .calTableContainer + div:empty {
      border: 0px;
    }
```
