### ISSUE TITLE
v7.0.0-b1 - events not displayed correctly for single day

### ISSUE THREAD

**Issue by marksie1988** [totaldebug/atomic-calendar-revive#572]
### Discussed in https://github.com/totaldebug/atomic-calendar-revive/discussions/571

<div type='discussions-op-text'>

<sup>Originally posted by **BebeMischa** March  3, 2022</sup>
Something wrong with display of Today.

with 6.2.0 : 
![calendar before](https://user-images.githubusercontent.com/73079275/156528646-cf6eaf1f-c2b2-4d32-8aa0-5530c1c47a68.PNG)

with 7.0.0-b1 no appointments today:
![calendar after](https://user-images.githubusercontent.com/73079275/156528771-04841d95-76f1-4cb6-9603-aa28f5657f2a.PNG)

code of that card:

```
type: custom:atomic-calendar-revive
entities:
  - entity: calendar.cistaplinka_live_nl
    titleColor: purple
    icon: mdi:home-heart
    color: purple
  - entity: calendar.maasisa2_gmail_com
    titleColor: violet
    icon: mdi:hospital
    color: violet
  - entity: calendar.feestdagen_in_nederland
    titleColor: orange
    icon: mdi:cheese
    color: orange
  - entity: calendar.feestdagen_in_tsjechie
    titleColor: cyan
    icon: mdi:glass-mug-variant
    color: cyan
  - entity: calendar.islamitische_feestdagen
    titleColor: white
    icon: mdi:mosque
    color: white
  - entity: calendar.feestdagen_in_suriname
    titleColor: goldenrod
    icon: mdi:emoticon-cool-outline
    color: goldenrod
enableModeChange: true
firstDayOfWeek: 1
maxDaysToShow: 1
refreshInterval: 180
name: Vandaag
showDeclined: true
sortByStartTime: true
noEventText: Er zijn geen afspraken vandaag
showWeekDay: true
showNoEventsForToday: true
showFullDayProgress: true
showEventIcon: true
hoursFormat: HH:mm
showDate: true
untilText: tot
fullDayEventText: hele dag
noEventsForNextDaysText: Er zijn geen afspraken aankomende dagen
hiddenEventText: verborgen
showHiddenText: true
showProgressBar: true
```
</div>
