### ISSUE TITLE
Description and Location are not shown in the new version 2022.5.0

### ISSUE THREAD

**Issue by jjprz** [totaldebug/atomic-calendar-revive#649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Description and Location are not shown in the new version 2022.5.0

![image](https://user-images.githubusercontent.com/17064130/167292675-00f4113a-5426-478e-989e-89df38dacaef.png)

### Expected behaviour

It is expected that the location will be shown on the right and below the description

### Card Version

7.0.0-b3

### Home Assistant Version

2022.5.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Without a copy of the configuration you have for the card I won't be able to troubleshoot this.

**Comment by jjprz** [comment]
```
          - type: custom:atomic-calendar-revive
            name: 'Próximos eventos: ⚽ 🎾'
            showMonth: true
            showWeekDay: true
            showDescription: true
            disableLocationLink: true
            refreshInterval: 600
            europeanDate: true
            showRelativeTime: false
            showProgressBar: false
            maxDaysToShow: 60
            timeSize: 80
            showHiddenText: false
            #maxEventCount: 3
            hideFinishedEvents: true
            cardHeight: 317px
            entities:
            - entity: calendar.deportes
              allowlist: 'vs'
```
