### ISSUE TITLE
Calendar card showing multi-day event past the end day

### ISSUE THREAD

**Issue by LordMike** [totaldebug/atomic-calendar-revive#754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have an event from my kids daycare describing our vacation, and it extends until tomorrow (monday) at 23:59, where it should end today (sunday) at 23:59. I checked the ICS feed we got from the daycare (Danish Aula.dk), and it shows up correctly. 

## Actual behaviour
I get the following on my display, it's clearly visible that the "Ferie/Fri" event stretches until monday (tomorrow), and doesn't stop on sunday (today). It's also shown to run till 23:59, which I think precludes timezone issues (Which I originally thought this was).

![image](https://user-images.githubusercontent.com/1027111/180662485-dd6dbc43-bdb3-4bef-bb90-df73d0e6d787.png)

## Details 
From the feed I have, I get the following. I'm not sure how to read ICS feeds correctly, but there is some amibiguity, for example `DTSTAMP` says `2022-07-24T00:00:21 Zulu`, which would mean `2022-07-24 02:00:21 Europe/Copenhagen`. Then on the other hand, `DTEND` has my local timezone, and `2022-07-24 23:59:00` - so I'm not sure what to think.
```
BEGIN:VEVENT
ATTENDEE;CN=....redacted...;PARTSTAT=ACCEPTED;ROLE=REQ-P
 ARTICIPANT:MAILTO:....redacted...
DESCRIPTION:....redacted...
DTEND;TZID=Europe/Copenhagen:20220724T235900
DTSTAMP:20220724T000021Z
DTSTART;TZID=Europe/Copenhagen;VALUE=DATE:20220707
ORGANIZER;CN=....redacted...
SEQUENCE:0
SUMMARY:Ferie/fri
UID:6e8c49f8-4873-4c4a-a66e-673f62999e59
END:VEVENT
```

My Home assistant calendar translates that to the following sensor with attributes. Unlike the feed, this calendar has the proper end date (local time).

```
Sensor: calendar.redacted_name

## Attributes:
message: Ferie/fri
all_day: false
start_time: 2022-07-07 00:00:00
end_time: 2022-07-24 23:59:00
location: null
description: ...redacted...
offset_reached: false
friendly_name: ...redacted...
```

## Browser:
I'm running an English language browser (so the week numbers are also off - but that's irrelevant :)). My local timezone is also Danish (Europe/Copenhagen, UTC +2).

### Expected behaviour

I expected, of course, the multi day event to stop on sunday. :)

Possibly related: #416, but my event is not an `all_day` event.

### Steps To Reproduce

I suspect it's reproducible by creating an event like mine above, and then showing the calendar.

### Card Version

v7.0.1

### Home Assistant Version

2022.7.6

### Configuration

```shell
type: custom:atomic-calendar-revive
entities:
  - entity: calendar.nemlig
    name: Nemlig
  - entity: calendar.htk_renovation
    name: HTK
  - entity: ...redacted.. (irrelevant)
    name: Aula
  - entity: ...redacted.. (irrelevant)
    name: S/O
  - entity: ...redacted.. (irrelevant)
    name: Michael
icon: mdi:calendar-month
showCalendarName: true
showWeekDay: true
sortByStartTime: true
showDate: true
dateFormat: dddd, DD MMMM HH:mm
hoursFormat: HH:mm
maxDaysToShow: 6
refreshInterval: 60
showWeekNumber: true
disableLocationLink: true
disableEventLink: true
showNoEventsForToday: true
dimFinishedEvents: true
fullDayEventText: Hele dagen
noEventText: Ingen events
showProgressBar: false
hideFinishedEvents: true
showRelativeTime: true
hideDuplicates: true
showMultiDay: true
showMultiDayEventParts: true
showCurrentEventLine: false
noEventsForNextDaysText: Ingen kalender info
firstDayOfWeek: 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by phlepper** [comment]
I have this same problem with Google Calendar.  I have several "All Day" events that span multiple days and all show an extra day for the total days and extend to the next day.

As an example, I have an event called 'Ashley Here' as an all-day event from August 19 to August 21 (3 days).

In Atomic Calendar, it is showing as 

```
Fri (19):
  Ashley Here (1/4)
  12:00 AM - 11:59 PM
Sat (20):
  Ashley Here (2/4)
  All Day, until 22 August
Sun (21):
  Ashley Here (3/4)
  All Day
Mon (22):
  Ashley Here (4/4)
  All Day
```

My configuration is:

```
type: custom:atomic-calendar-revive
entities:
  - entity: calendar.holidays_in_united_states
    name: Holidays in United States
  - entity: calendar.2019_colorado_free_days
    name: 2019 Colorado Free Days
  - entity: calendar.chicago_bears
    name: Chicago Bears
  - entity: calendar.xxxxx_gmail_com
    name: xxxxx@gmail.com
  - entity: calendar.yyyyy_gmail_com
    name: yyyyy@gmail.com
  - entity: calendar.denver_broncos
    name: Denver Broncos
  - entity: calendar.zzzzz
    name: Zzzzz
  - entity: calendar.aaaaa
    name: Aaaaaa
name: Calendar
enableModeChange: true
firstDayOfWeek: 1
maxDaysToShow: 15
refreshInterval: 60
hideFinishedEvents: false
showMultiDay: true
showDate: true
sortByStartTime: true
showMultiDayEventParts: true
calShowDescription: true
showCalendarName: false
showEventIcon: true
showNoEventsForToday: false
showWeekDay: true
showMonth: false
showCurrentEventLine: false
showProgressBar: false
disableEventLink: true
disableLocationLink: true
showLastCalendarWeek: false
disableCalEventLink: true
disableCalLocationLink: true
disableCalLink: true
```

Let me know if you need additional information for debugging or if you need my help for testing any changes.

Thanks!
Paul
