### ISSUE TITLE
Calendar Mode not showing dots for each day

### ISSUE THREAD

**Issue by JazzMan808** [totaldebug/atomic-calendar-revive#844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am not seeing any icons / dots for where there is an event, it appears blank.
![image](https://user-images.githubusercontent.com/83962692/200969804-ccd8c809-25a0-44a3-85a6-0803aedc7959.png)

### Expected behaviour

I expect to see dots / icons for each day there is an event in Calendar Mode

### Steps To Reproduce

1. Installed Plugin
2. Assigned Entity
3. my configuration
4.      - type: custom:atomic-calendar-revive
        defaultMode: Calendar
        entities:
          - entity: calendar.your_family_account1
        enableModeChange: true
        showDate: true
        showWeekDay: true
        firstDayOfWeek: 1
        showLoader: true
        showRelativeTime: true
        showMultiDay: true
        showWeekNumber: true
        disableCalLink: true

### Card Version

7.0.1

### Home Assistant Version

2022.11.2

### Configuration

```shell
4.      - type: custom:atomic-calendar-revive
        defaultMode: Calendar
        entities:
          - entity: calendar.your_family_account1
        enableModeChange: true
        showDate: true
        showWeekDay: true
        firstDayOfWeek: 1
        showLoader: true
        showRelativeTime: true
        showMultiDay: true
        showWeekNumber: true
        disableCalLink: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Hi there,

You need to add an icon to the entity. 

```
     - type: custom:atomic-calendar-revive
        defaultMode: Calendar
        entities:
          - entity: calendar.your_family_account1
            Icon: mdi-user
        enableModeChange: true
        showDate: true
        showWeekDay: true
        firstDayOfWeek: 1
        showLoader: true
        showRelativeTime: true
        showMultiDay: true
        showWeekNumber: true
        disableCalLink: true
```
