### ISSUE TITLE
Calendar name dont show up

### ISSUE THREAD

**Issue by rhgiter** [totaldebug/atomic-calendar-revive#849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

no calendar name

### Expected behaviour

to see calendar name :-)

### Card Version

newest

### Home Assistant Version

2022.11.2

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Calendar Card
entities:
  - calendar.2
  - calendar.1
enableModeChange: true
showCalendarName: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rhgiter** [comment]
like this ?  both dont work 


type: custom:atomic-calendar-revive
name: Calendar Card
entities:
  - calendar.faelles_1
  - name: TEST NAME

or 

type: custom:atomic-calendar-revive
name: Calendar Card
entities:
  - calendar.faelles_1
    name: TEST NAME

**Comment by marksie1988** [comment]
```
type: custom:atomic-calendar-revive
name: Calendar Card
entities:
  - calendar.2
    name: Cal 1
  - calendar.1
    name: Cal 2
enableModeChange: true
showCalendarName: true
```

I have tested this config in my home assistant and all shows as expected.
