### ISSUE TITLE
Partial locale detection

### ISSUE THREAD

**Issue by Fredzxda** [totaldebug/atomic-calendar-revive#875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Even if locale 'fr' seems to be present in the repository, the translation is not done on the display. I have to manually set all of them in the configuration. And "Week" can't be forced into "semaine" as no option exist.
Option in the configuration card can help to force locale.

### Expected behaviour

Automatic translation for fr locale

### Card Version

7.01

### Home Assistant Version

2022.12.6

### Configuration

```shell
type: custom:atomic-calendar-revive
    enableModeChange: true
    firstDayOfWeek: 1
    maxDaysToShow: 365
    refreshInterval: 60
    showDeclined: false
    hideFinishedEvents: true
    showRelativeTime: true
    showMultiDay: true
    showCalendarName: false
    showEventIcon: true
    showNoEventsForToday: true
    showWeekDay: true
    showHiddenText: true
    showWeekNumber: true
    calShowDescription: true
    disableCalEventLink: true
    showLastCalendarWeek: true
    entities:
      - entity: calendar.weather_for_sajas
        name: Weather for sajas
      - entity: calendar.homeassistantagenda
        name: Homeassistantagenda
    dimFinishedEvents: true
    disableCalLocationLink: false
    untilText: Jusqu'à
    noEventsForNextDaysText: Pas de rendez-vous dans les prochains jours
    noEventText: Pas de rendez-vous aujourd'hui
    hiddenEventText: Rendez-vous masqué
    showCurrentEventLine: true
    showMonth: true
    showFullDayProgress: true
    name: Agenda
    sortByStartTime: true
    showDate: true
    hideDuplicates: true
    showMultiDayEventParts: true
    disableCalLink: true
    fullDayEventText: Journée entière
    disableEventLink: true
    disableLocationLink: false
    cardHeight: 100%
    europeanDate: true
    dateFormat: LL
    showLocation: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Just tested and this works as expected: 

![image](https://user-images.githubusercontent.com/159166/209828971-60a52361-0f2c-4918-a82e-d794502c1641.png)

ensure you have the user language is set correctly: 

![image](https://user-images.githubusercontent.com/159166/209829094-edc8326a-308f-4f74-9439-5134b35b80dc.png)

**Comment by Fredzxda** [comment]
Hello Steven,
Thank you for your answer. I verified the language and it is set to
Français. Updated to 7.2.0. However, the translation is not performed. I
have manually translated everything I can. But no option for week.
Following, the screenshot of my laptop. The same on my Samsung Galaxy Tab
S2 and my Asus Rog Phone 5s.
[image: image.png]
[image: image.png]
[image: image.png]
Do you know what I miss ?

Best Regards.

Le mer. 28 déc. 2022 à 15:43, Steven Marks ***@***.***> a
écrit :

**Comment by Fredzxda** [comment]
I tested with all translations removed in the UI. The Dates are correctly
formatted using French language. But the other information not.

[image: image.png]

Le jeu. 29 déc. 2022 à 08:14, Frédéric Duloum ***@***.***> a
écrit :

**Comment by marksie1988** [comment]
Is this the same if you upgrade to the latest version of the card?

I will add an option to manually set the week name anyway.

**Comment by marksie1988** [comment]
Also worth clearing the browser cache, sometimes it doesn't notice the changes and still uses the old language until quite a few refreshes.

**Comment by Fredzxda** [comment]
Hi,
Clearing the browser cache doesn't change anything.
What can I test to help solving this ?


Le jeu. 29 déc. 2022 à 09:34, Steven Marks ***@***.***> a
écrit :

**Comment by marksie1988** [comment]
One thing to check is that the card thinks it is using French, if you press f12 and go to console you should see a line for atomic-calendar-revive that shows the version and the language it thinks it has loaded.

**Comment by stefankoehne** [comment]
Hi,
same issue here with German / locale "de".
The "in 11 Minutes" is translated fine. But no automatic translation for "fullDayEventText" and Week.

Console: ` atomic-calendar-revive  Version: 7.2.0  de`
Config:
```
type: custom:atomic-calendar-revive
name: Dienstplan
maxDaysToShow: 3
showWeekDay: true
showMonth: true
disableEventLink: true
disableLocationLink: true
fullDayEventText: ganztägig
untilText: noch bis
europeanDate: true
showCalendarName: true
showWeekNumber: true
noEventsForNextDaysText: keine Termine
entities:
  - entity: calendar.stefan_dienst
    name: Stefan Dienst
    color: cyan
  - entity: calendar.stefan_frei
    name: Stefan Frei
    color: lightgreen
  - entity: calendar.johanna_dienst
    name: Johanna Dienst
    color: magenta
  - entity: calendar.johanna_frei
    name: Johanna Frei
    color: lightgreen
firstDayOfWeek: 1
refreshInterval: 60
dimFinishedEvents: false
```
![Screenshot_2](https://user-images.githubusercontent.com/69876166/221442149-29ec37a9-9435-48f2-bf97-9fb62aa8fc39.jpg)
